# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-24 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('director', models.CharField(max_length=200)),
                ('imdb_score', models.FloatField(blank=True, default=None, null=True)),
                ('popularity', models.FloatField(blank=True, default=None, null=True)),
                ('image_url', models.URLField(null=True)),
                ('featured_image', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(to='movieApp.Genre')),
            ],
        ),
    ]
